name: Code Quality Control

on:
  push:
    branches: ['*']

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Run Prettier to check code formatting
      - name: Run Prettier
        run: npm run prettier-check

      # Run ESLint to check for linting errors
      - name: Run ESLint
        run: npm run lint

      # Run Vitest for unit testing
      - name: Run Vitest
        run: npm run test
